# ---
# jobs:
# - name: job
#   public: true
#   plan:
#   - task: simple-task
#     config:
#       platform: linux
#       image_resource:
#         type: registry-image
#         source: { repository: busybox }
#       run:
#         path: echo
#         args: ["Hello world!"]

---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/Bajocode/searchengine.git

jobs:
- name: bullshit
  plan:
  - get: repo
    trigger: true
  - task: bullshit
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: repo
      run:
        path: find
        args: ["."]
