version: '3.5'

services:
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v19.2.2
    ports:
    - "26257:26257"
    - "8080:8080"
    command: start-single-node --insecure
    volumes:
    - "${PWD}/.data/cockroachdb:/cockroach/cockroach-data"
    - "${PWD}/migrations:/cockroach/cockroach-data/migrations"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    volumes:
    - "${PWD}/.data/elasticsearch:/usr/share/elasticsearch/data"
